# coding: utf-8

"""
    VIRL STD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import virl
from virl.rest import ApiException
from virl.apis.health_check_api import HealthCheckApi


class TestHealthCheckApi(unittest.TestCase):
    """ HealthCheckApi unit test stubs """

    def setUp(self):
        self.api = virl.apis.health_check_api.HealthCheckApi()

    def tearDown(self):
        pass

    def test_simengine_rest_health_delete(self):
        """
        Test case for simengine_rest_health_delete

        Cancel running health check.
        """
        pass

    def test_simengine_rest_health_get(self):
        """
        Test case for simengine_rest_health_get

        Retrieve current health check status and results.
        """
        pass

    def test_simengine_rest_health_put(self):
        """
        Test case for simengine_rest_health_put

        Run health check
        """
        pass


if __name__ == '__main__':
    unittest.main()
