# coding: utf-8

"""
    VIRL STD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import virl
from virl.rest import ApiException
from virl.apis.interfaces_api import InterfacesApi


class TestInterfacesApi(unittest.TestCase):
    """ InterfacesApi unit test stubs """

    def setUp(self):
        self.api = virl.apis.interfaces_api.InterfacesApi()

    def tearDown(self):
        pass

    def test_simengine_rest_interfaces_simulation_get(self):
        """
        Test case for simengine_rest_interfaces_simulation_get

        List simulation interfaces.
        """
        pass

    def test_simengine_rest_update_interfaces_simulation_put(self):
        """
        Test case for simengine_rest_update_interfaces_simulation_put

        Update simulation nodes interfaces admin_state.
        """
        pass


if __name__ == '__main__':
    unittest.main()
