# coding: utf-8

"""
    VIRL STD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import virl
from virl.rest import ApiException
from virl.apis.autonetkit_api import AutonetkitApi


class TestAutonetkitApi(unittest.TestCase):
    """ AutonetkitApi unit test stubs """

    def setUp(self):
        self.api = virl.apis.autonetkit_api.AutonetkitApi()

    def tearDown(self):
        pass

    def test_ank_rest_process_post(self):
        """
        Test case for ank_rest_process_post

        Process a VIRL XML Topology
        """
        pass

    def test_ank_rest_test_get(self):
        """
        Test case for ank_rest_test_get

        Verify the user is authenticated and return autonetkit API version. Also displays installed AutoNetkit version
        """
        pass


if __name__ == '__main__':
    unittest.main()
