# coding: utf-8

"""
    VIRL STD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import virl
from virl.rest import ApiException
from virl.apis.snapshot_api import SnapshotApi


class TestSnapshotApi(unittest.TestCase):
    """ SnapshotApi unit test stubs """

    def setUp(self):
        self.api = virl.apis.snapshot_api.SnapshotApi()

    def tearDown(self):
        pass

    def test_simengine_rest_snapshot_simulation_node_post(self):
        """
        Test case for simengine_rest_snapshot_simulation_node_post

        Create snapshot of a node
        """
        pass


if __name__ == '__main__':
    unittest.main()
