# coding: utf-8

"""
    VIRL STD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import virl
from virl.rest import ApiException
from virl.apis.traffic_counters_api import TrafficCountersApi


class TestTrafficCountersApi(unittest.TestCase):
    """ TrafficCountersApi unit test stubs """

    def setUp(self):
        self.api = virl.apis.traffic_counters_api.TrafficCountersApi()

    def tearDown(self):
        pass

    def test_simengine_rest_counters_simulation_id_get(self):
        """
        Test case for simengine_rest_counters_simulation_id_get

        List traffic on particular interfaces.
        """
        pass


if __name__ == '__main__':
    unittest.main()
