# coding: utf-8

"""
    VIRL STD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import virl
from virl.rest import ApiException
from virl.apis.node_resources_api import NodeResourcesApi


class TestNodeResourcesApi(unittest.TestCase):
    """ NodeResourcesApi unit test stubs """

    def setUp(self):
        self.api = virl.apis.node_resources_api.NodeResourcesApi()

    def tearDown(self):
        pass

    def test_openstack_rest_create_port_post(self):
        """
        Test case for openstack_rest_create_port_post

        Create a port on an OpenStack network
        """
        pass

    def test_openstack_rest_flavors_get(self):
        """
        Test case for openstack_rest_flavors_get

        Return information about currently installed OpenStack VM flavors. This information is mainly for use in the topology design phase in GUI.
        """
        pass

    def test_openstack_rest_images_get(self):
        """
        Test case for openstack_rest_images_get

        Return information about currently installed OpenStack VM images. This information is mainly for use in the topology design phase in GUI.
        """
        pass

    def test_openstack_rest_networks_get(self):
        """
        Test case for openstack_rest_networks_get

        Return information about OpenStack networks.
        """
        pass

    def test_openstack_rest_ports_network_name_get(self):
        """
        Test case for openstack_rest_ports_network_name_get

        Return information about the ports of an OpenStack network.
        """
        pass

    def test_openstack_rest_test_get(self):
        """
        Test case for openstack_rest_test_get

        Verify the user is authenticated and return openstack API version.
        """
        pass

    def test_openstack_rest_volumes_get(self):
        """
        Test case for openstack_rest_volumes_get

        Return information about VM volumes present in OpenStack. Volume snapshots are not listed here. This information is mainly for use in the topology design phase in GUI.
        """
        pass


if __name__ == '__main__':
    unittest.main()
