# coding: utf-8

"""
    VIRL STD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import virl
from virl.rest import ApiException
from virl.apis.catalog_api import CatalogApi


class TestCatalogApi(unittest.TestCase):
    """ CatalogApi unit test stubs """

    def setUp(self):
        self.api = virl.apis.catalog_api.CatalogApi()

    def tearDown(self):
        pass

    def test_root_get(self):
        """
        Test case for root_get

        List all supported URL rules and their associated methods
        """
        pass


if __name__ == '__main__':
    unittest.main()
