# coding: utf-8

"""
    VIRL STD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import virl
from virl.rest import ApiException
from virl.apis.volume_api import VolumeApi


class TestVolumeApi(unittest.TestCase):
    """ VolumeApi unit test stubs """

    def setUp(self):
        self.api = virl.apis.volume_api.VolumeApi()

    def tearDown(self):
        pass

    def test_simengine_rest_simulation_node_attach_volume_get(self):
        """
        Test case for simengine_rest_simulation_node_attach_volume_get

        Attach volume to a running node.
        """
        pass

    def test_simengine_rest_simulation_node_detach_volume_get(self):
        """
        Test case for simengine_rest_simulation_node_detach_volume_get

        Detach volume from a running node.
        """
        pass


if __name__ == '__main__':
    unittest.main()
