# coding: utf-8

"""
    VIRL STD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import virl
from virl.rest import ApiException
from virl.apis.admin_api import AdminApi


class TestAdminApi(unittest.TestCase):
    """ AdminApi unit test stubs """

    def setUp(self):
        self.api = virl.apis.admin_api.AdminApi()

    def tearDown(self):
        pass

    def test_simengine_rest_admin_list_user_get(self):
        """
        Test case for simengine_rest_admin_list_user_get

        Get a list of all currently launched simulations
        """
        pass

    def test_simengine_rest_admin_stop_user_simulation_put(self):
        """
        Test case for simengine_rest_admin_stop_user_simulation_put

        Stop a particular simulation or set of simulations
        """
        pass

    def test_simengine_rest_admin_update_simulation_expiry_put(self):
        """
        Test case for simengine_rest_admin_update_simulation_expiry_put

        Update simulation expiration
        """
        pass

    def test_simengine_rest_jobs_get(self):
        """
        Test case for simengine_rest_jobs_get

        Get current job processing information
        """
        pass

    def test_simengine_rest_licensing_get(self):
        """
        Test case for simengine_rest_licensing_get

        Get information on licensing
        """
        pass

    def test_simengine_rest_systemlogs_get(self):
        """
        Test case for simengine_rest_systemlogs_get

        Get a zip-file of all current logs
        """
        pass

    def test_simengine_rest_test_get(self):
        """
        Test case for simengine_rest_test_get

        List simengine API version and features, compatibility check
        """
        pass


if __name__ == '__main__':
    unittest.main()
