# coding: utf-8

"""
    VIRL STD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import virl
from virl.rest import ApiException
from virl.apis.traffic_capture_api import TrafficCaptureApi


class TestTrafficCaptureApi(unittest.TestCase):
    """ TrafficCaptureApi unit test stubs """

    def setUp(self):
        self.api = virl.apis.traffic_capture_api.TrafficCaptureApi()

    def tearDown(self):
        pass

    def test_simengine_rest_capture_simulation_delete(self):
        """
        Test case for simengine_rest_capture_simulation_delete

        Delete a traffic capture.
        """
        pass

    def test_simengine_rest_capture_simulation_get(self):
        """
        Test case for simengine_rest_capture_simulation_get

        List available traffic captures, or fetch captured data.
        """
        pass

    def test_simengine_rest_capture_simulation_post(self):
        """
        Test case for simengine_rest_capture_simulation_post

        Create a new traffic capture
        """
        pass


if __name__ == '__main__':
    unittest.main()
