# coding: utf-8

"""
    VIRL STD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import virl
from virl.rest import ApiException
from virl.apis.simengine_api import SimengineApi


class TestSimengineApi(unittest.TestCase):
    """ SimengineApi unit test stubs """

    def setUp(self):
        self.api = virl.apis.simengine_api.SimengineApi()

    def tearDown(self):
        pass

    def test_simengine_rest_calculate_requirements_post(self):
        """
        Test case for simengine_rest_calculate_requirements_post

        Calculate hardware requirements
        """
        pass

    def test_simengine_rest_events_simulation_get(self):
        """
        Test case for simengine_rest_events_simulation_get

        Return a list of recent events recorded for a simulation
        """
        pass

    def test_simengine_rest_export_simulation_get(self):
        """
        Test case for simengine_rest_export_simulation_get

        Retrieve original VIRL XML Topology file
        """
        pass

    def test_simengine_rest_launch_post(self):
        """
        Test case for simengine_rest_launch_post

        Create a new simulation
        """
        pass

    def test_simengine_rest_list_get(self):
        """
        Test case for simengine_rest_list_get

        Get a list of all simulations of this user, and the status of each simulation.
        """
        pass

    def test_simengine_rest_nodes_simulation_get(self):
        """
        Test case for simengine_rest_nodes_simulation_get

        List simulation nodes.
        """
        pass

    def test_simengine_rest_serial_port_simulation_get(self):
        """
        Test case for simengine_rest_serial_port_simulation_get

        Return links to VM node serial ports.
        """
        pass

    def test_simengine_rest_status_simulation_get(self):
        """
        Test case for simengine_rest_status_simulation_get

        Return the status of a launched simulation
        """
        pass

    def test_simengine_rest_stop_simulation_get(self):
        """
        Test case for simengine_rest_stop_simulation_get

        Schedule complete stop of a launched simulation
        """
        pass

    def test_simengine_rest_tracking_post(self):
        """
        Test case for simengine_rest_tracking_post

        Authorize a new simulation tracking channel
        """
        pass

    def test_simengine_rest_tracking_tracking_id_delete(self):
        """
        Test case for simengine_rest_tracking_tracking_id_delete

        Deauthorize a simulation tracking channel.
        """
        pass

    def test_simengine_rest_tracking_tracking_id_get(self):
        """
        Test case for simengine_rest_tracking_tracking_id_get

        Retrieve information on a simulation tracking channel
        """
        pass

    def test_simengine_rest_update_simulation_start_get(self):
        """
        Test case for simengine_rest_update_simulation_start_get

        Start simulation nodes previously stopped by simengine-update-stop
        """
        pass

    def test_simengine_rest_update_simulation_stop_put(self):
        """
        Test case for simengine_rest_update_simulation_stop_put

        Stop simulation nodes without tearing down the simulation
        """
        pass

    def test_simengine_rest_updates_get(self):
        """
        Test case for simengine_rest_updates_get

        Get a list of all simulations of this user, and the status of each simulation.
        """
        pass

    def test_simengine_rest_vnc_console_simulation_get(self):
        """
        Test case for simengine_rest_vnc_console_simulation_get

        Return links to VM node VNC consoles
        """
        pass


if __name__ == '__main__':
    unittest.main()
